import type { Section } from "./types";

export const formativos: Section[] = [
  {
    name: "Baby Gym",
    level: "Zafiro F1",
    ageRange: "1 a 3 años y 11 meses",
    schedule: "SÁB 12:30 a 13:30 hrs",
    hours: "1H x semana",
    price: 50000,
    color: "bg-gradient-to-br from-blue-400 to-blue-600",
    category: "formativo",
  },
  {
    name: "Sección Magenta",
    level: "F3",
    ageRange: "3,5 a 6 años",
    schedule: "Lu-Mi 15:00 a 16:00 hrs",
    hours: "2H x semana",
    price: 50000,
    noSpots: true,
    color: "bg-gradient-to-br from-pink-400 to-pink-600",
    category: "formativo",
  },
  {
    name: "Sección Turquesa",
    level: "F3",
    ageRange: "4 a 6 años",
    schedule: "SÁB 11:00 a 12:00 hrs",
    hours: "1H x semana",
    price: 45000,
    noSpots: true,
    color: "bg-gradient-to-br from-teal-400 to-teal-600",
    category: "formativo",
  },
  {
    name: "Sección Púrpura",
    level: "F3",
    ageRange: "4 a 5 años",
    schedule: "Ma-Ju 15:00 a 16:00 hrs",
    hours: "2H x semana",
    price: 50000,
    color: "bg-gradient-to-br from-purple-400 to-purple-600",
    category: "formativo",
  },
  {
    name: "Sección Celeste",
    level: "F3",
    ageRange: "4 a 6 años",
    schedule: "SÁB 12:00 a 13:00 hrs",
    hours: "1H x semana",
    price: 45000,
    color: "bg-gradient-to-br from-sky-400 to-sky-600",
    category: "formativo",
  },
  {
    name: "Sección Burdeo",
    level: "F4",
    ageRange: "6 a 10 años",
    schedule: "Ma-Ju 16:00 a 17:00 hrs",
    hours: "2H x semana",
    price: 50000,
    hasPromo: true,
    promoDetails:
      "Matrícula 20% descuento + Mensualidad 20% descuento por 3 meses",
    color: "bg-gradient-to-br from-red-600 to-red-800",
    category: "formativo",
  },
  {
    name: "Sección Amarillo",
    level: "F4",
    ageRange: "7 a 12 años",
    schedule: "Lu-Mi 16:00 a 17:00 hrs",
    hours: "2H x semana",
    price: 50000,
    noSpots: true,
    color: "bg-gradient-to-br from-yellow-400 to-yellow-600",
    category: "formativo",
  },
  {
    name: "Sección Rosado",
    level: "F4",
    ageRange: "7 a 12 años",
    schedule: "Ma-Ju 17:30 a 19:00 hrs",
    hours: "3H x semana",
    price: 55000,
    noSpots: true,
    color: "bg-gradient-to-br from-rose-400 to-rose-600",
    category: "formativo",
  },
  {
    name: "Sección Azul",
    level: "F4",
    ageRange: "7 a 12 años",
    schedule: "SÁB 09:00 a 11:00 hrs",
    hours: "2H x semana",
    price: 50000,
    noSpots: true,
    color: "bg-gradient-to-br from-blue-500 to-blue-700",
    category: "formativo",
  },
  {
    name: "Sección Azul (Varones)",
    level: "F4",
    ageRange: "7 a 12 años",
    schedule: "SÁB 09:00 a 12:00 hrs",
    hours: "3H x semana",
    price: 55000,
    noSpots: true,
    color: "bg-gradient-to-br from-blue-600 to-blue-800",
    category: "formativo",
  },
  {
    name: "Sección Naranja",
    level: "F5",
    ageRange: "13 años y más, Juvenil y adulto",
    schedule: "Ma-Ju 19:00 a 21:00 hrs",
    hours: "4H x semana",
    price: 60000,
    noSpots: true,
    color: "bg-gradient-to-br from-orange-400 to-orange-600",
    category: "formativo",
  },
  {
    name: "Sección Marrón (Varones)",
    level: "F5",
    ageRange: "13 años y más, Juvenil y adultos",
    schedule: "Lu-Mi-Vi inicio 17:00 o 18:00 hrs",
    hours: "2hrs x clase, 6H x semana",
    price: 70000,
    color: "bg-gradient-to-br from-amber-600 to-amber-800",
    category: "formativo",
  },
];

export const avanzados: Section[] = [
  {
    name: "Sección Violeta",
    level: "Avanzado - Damas",
    ageRange: "Con experiencia técnica",
    schedule: "Ma-Ju 17:00 a 19:00 hrs",
    hours: "4H x semana",
    price: 60000,
    noSpots: true,
    color: "bg-gradient-to-br from-violet-500 to-violet-700",
    category: "avanzado",
  },
  {
    name: "Sección Rojo",
    level: "Avanzado - Varones",
    ageRange: "Con experiencia técnica",
    schedule: "Lu-Mi-Vi 18:00 a 20:00 hrs",
    hours: "6H x semana",
    price: 70000,
    color: "bg-gradient-to-br from-red-500 to-red-700",
    category: "avanzado",
  },
  {
    name: "Sección Verde",
    level: "Avanzado - Damas",
    ageRange: "Con experiencia técnica",
    schedule: "Lu-Mi-Vi 16:00 a 18:00 hrs",
    hours: "6H x semana",
    price: 70000,
    color: "bg-gradient-to-br from-green-500 to-green-700",
    category: "avanzado",
  },
  {
    name: "Sección Cian",
    level: "Avanzado - Damas",
    ageRange: "Con experiencia técnica",
    schedule: "Lu-Mi 17:30 a 20:00, Vi 17:30 a 19:00 hrs",
    hours: "6:30H x semana",
    price: 73000,
    color: "bg-gradient-to-br from-cyan-500 to-cyan-700",
    category: "avanzado",
  },
  {
    name: "Sección Morado",
    level: "Avanzado - Damas",
    ageRange: "Con experiencia técnica",
    schedule: "Lu-Mi 18:00 a 20:00, Vi 16:00 a 18:00 hrs",
    hours: "6H x semana",
    price: 70000,
    color: "bg-gradient-to-br from-indigo-500 to-indigo-700",
    category: "avanzado",
  },
  {
    name: "Sección Fucsia",
    level: "Elite - Damas",
    ageRange: "Nivel Elite",
    schedule: "Lu-Ma-Ju-Vi 17:00 a 20:00 hrs",
    hours: "12H x semana",
    price: 95000,
    noSpots: true,
    color: "bg-gradient-to-br from-fuchsia-500 to-fuchsia-700",
    category: "avanzado",
  },
];
